name: playlistmerger4spotify
description: "PlaylistMerger 4 Spotify"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.8.251214-2+202512142

environment:
  sdk: ^3.9.0

# to update generate files:
# dart run build_runner watch --delete-conflicting-outputs

# to generate translations from i10n folder, install the plugin Flutter Intl
# and run: dart run intl_utils:generate

# To see which dependencies have newer versions available, run `flutter pub outdated`.

dependencies:
  cached_network_image: ^3.4.1
  drift: ^2.28.1
  file_picker: ^10.3.1
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.4.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  intl_utils: ^2.8.11
  introduction_screen: ^3.1.17
  oauth2_client: ^4.2.0
  package_info_plus: ^8.3.1
  path: ^1.9.1
  path_provider: ^2.1.5
  provider: ^6.1.5
  share_plus: ^11.1.0
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  sqlite3_flutter_libs: ^0.5.39
  upgrader: ^11.5.0
  url_launcher: ^6.3.2
  workmanager: ^0.9.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: ^2.28.1
  build_runner: ^2.7.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/

flutter_intl:
  enabled: true
